### ISSUE TITLE
DBus Error Unknown Service

### ISSUE THREAD

**Issue by phodina** [PNDeb/pinenote-gnome-extension#1]
Hi @m-weigand,

I've packaged the extension for Alpine (postmarketOS) and modified the metadata.json to support GNOME Shell 44.

The extension is now compatible and initializes.

However, it ends with an error:
```
Gio.DBusError.GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.pinenote.ebc was not provided by any .service files
```
The DBus XML configuration is located here
https://github.com/PNDeb/pinenote-gnome-extension/blob/main/pnhelper%40m-weigand.github.com/ebc.js#L9

Running the command gives me the same error:
```
dbus-send --system --print-reply --dest=org.pinenote.ebc
/ebc org.freedesktop.DBus.Introspectable.Introspect
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.pinenote.ebc was not provided by any .service files
```

Could you please advise how to install this extension? I haven't found anything more in the Debian packaging besides copy all the files. Is that the correct approach?

**Comment by m-weigand** [comment]
This here is my attempt to provide a dbus service for configuring pinenote-related stuff without having to add all the udev rules etc. For the future I wanted to also handle registering of the pen over that interface...

https://github.com/m-weigand/pinenote_dbus_service

**Comment by phodina** [comment]
Perfect, I'll package it and test it with the service running.

I don't have experience with DBus so can't say if it's the right approach but I like the idea of registering the pen and also having it as a standalone service that can be reused by other environments e.g. Plasma

**Comment by phodina** [comment]
So now the extension works and I'm able to change the waveforms.

Will update the PostmarketOS [MR](https://gitlab.com/postmarketOS/pmaports/-/merge_requests/4142).
